version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ftfy
    versions:
    - "5.8"
    - "5.9"
    - "6.0"
  - dependency-name: regex
    versions:
    - 2020.11.13
    - 2021.3.17
  - dependency-name: virtualenv
    versions:
    - 20.4.0
    - 20.4.2
    - 20.4.3
  - dependency-name: spacy
    versions:
    - 2.3.5
    - 3.0.0
    - 3.0.1
    - 3.0.3
    - 3.0.4
    - 3.0.5
  - dependency-name: python-socketio
    versions:
    - 5.0.4
    - 5.1.0
  - dependency-name: thinc
    versions:
    - 8.0.1
    - 8.0.2
  - dependency-name: tqdm
    versions:
    - 4.56.0
    - 4.56.1
    - 4.56.2
    - 4.57.0
    - 4.58.0
    - 4.59.0
  - dependency-name: amqp
    versions:
    - 5.0.5
  - dependency-name: pytz
    versions:
    - "2020.5"
  - dependency-name: packaging
    versions:
    - "20.8"
  - dependency-name: babel
    versions:
    - 2.9.0
  - dependency-name: billiard
    versions:
    - 3.6.3.0
  - dependency-name: gunicorn
    versions:
    - 20.0.4
  - dependency-name: jinja2
    versions:
    - 2.10.1
